[deps]
BagOfWords = "87b137f8-3b59-4550-8c54-1b47926674ff"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
InvertedFiles = "b20bd276-2c70-11ec-161a-3d1e1109a1c3"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
KNearestCenters = "4dca28ae-43b8-11eb-1f5e-d55054101997"
MLUtils = "f1d291b0-491e-4a28-83b9-f70985020b54"
SimilaritySearch = "053f045d-5466-53fd-b400-a066f88fe02a"
TextSearch = "7f6f6c8a-3b03-11e9-223d-e7d88259bd6c"
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"
